baseURL = 'http://example.org/'
languageCode = 'zh-cn'
title = '园子里的日光'
theme = 'hermeneutics'

[Permalinks]
    posts = "/:slug/"

[[menu.main]]
    identifier = "archives"
    name = "归档"
    weight = 10
    
[[menu.main]]
    identifier = "posts"
    name = "时间"
    url = "posts"
    weight = 10
    parent = "archives"

[[menu.main]]
    identifier = "category"
    name = "分类"
    url = "categories"
    weight = 10
    parent = "archives"

[[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "tags"
    weight = 10
    parent = "archives"

[[menu.main]]
    identifier = "links"
    name = "友链"
    url = "links"
    weight = 20

[[menu.main]]
    identifier = "whisper"
    name = "碎语"
    url = "whisper"
    weight = 30

[[menu.main]]
    identifier = "now"
    name = "如今"
    url = "now"
    weight = 40

[params]
    author = "Chlorine"
    bio = "Como el viento."
    tags = [
        "Undergraduate @ THU",
        "Open Source Enthusiast",
        "Indie Blogger",
        "Alt-History Writer",
        "Cyber Hermit"
    ]
    [params.twikoo]
        enable = true
        version = "1.6.41"
        envId = "https://tk.viento.cc"