baseURL = 'https://example.com/'
languageCode = 'en-us'
title = 'My Awesome Site'
theme = 'hermeneutics'

# 如果你使用 CJK（中文、日文、韩文）语言，请将下面的选项设置为 true
hasCJKLanguage = false
enableCsrf = false

[Permalinks]
    posts = "/:slug/"

[[menu.main]]
    identifier = "archives"
    name = "Archives"
    weight = 10

[[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "posts"
    weight = 10
    parent = "archives"

[[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "categories"
    weight = 10
    parent = "archives"

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "tags"
    weight = 10
    parent = "archives"

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "projects"
    weight = 20

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "about"
    weight = 30

[params]
    [params.basic]
        startDate = "01/01/2023 00:00:00"
        announcement = false
        math = false

    [params.author]
        name = "John Doe"
        homepage = "https://example.com/about"
        bio = "A passionate blogger."
        avatar = "/img/avatar.jpg"
        tags = [
            "Blogger",
            "Developer",
            "Open Source Enthusiast",
            "Tech Lover",
        ]
    [params.rss]
        fullText = false

    [[params.social]]
        name = "Home"
        url = "/"
        icon = "i-carbon-home"
        color = "#4A90E2"
        enable = true

    [[params.social]]
        name = "Email"
        url = "mailto:your-email@example.com"
        icon = "i-carbon-email"
        color = "#EA4335"
        enable = true

    [[params.social]]
        name = "RSS"
        url = "/index.xml"
        icon = "i-carbon-rss"
        color = "#EE802F"
        enable = true

    [[params.social]]
        name = "GitHub"
        url = "https://github.com/your-username"
        icon = "i-carbon-logo-github"
        color = "#181717"
        enable = true

    [[params.social]]
        name = "GitLab"
        url = "https://gitlab.com/your-username"
        icon = "i-carbon-logo-gitlab"
        color = "#FC6D26"
        enable = false

    [[params.social]]
        name = "Codeberg"
        url = "https://codeberg.org/your-username"
        icon = "i-simple-codeberg"
        color = "#2185D0"
        enable = false

    [[params.social]]
        name = "Twitter"
        url = "https://twitter.com/your-username"
        icon = "i-carbon-logo-twitter"
        color = "#1DA1F2"
        enable = false

    [[params.social]]
        name = "Facebook"
        url = "https://facebook.com/your-username"
        icon = "i-carbon-logo-facebook"
        color = "#1877F2"
        enable = false

    [[params.social]]
        name = "Instagram"
        url = "https://instagram.com/your-username"
        icon = "i-carbon-logo-instagram"
        color = "#E4405F"
        enable = false

    [[params.social]]
        name = "LinkedIn"
        url = "https://linkedin.com/in/your-username"
        icon = "i-carbon-logo-linkedin"
        color = "#0A66C2"
        enable = false

    [[params.social]]
        name = "YouTube"
        url = "https://www.youtube.com/channel/your-channel"
        icon = "i-carbon-logo-youtube"
        color = "#FF0000"
        enable = false

    [[params.social]]
        name = "Bilibili"
        url = "https://space.bilibili.com/your-userid"
        icon = "i-simple-bilibili"
        color = "#00A1D6"
        enable = false

    [[params.social]]
        name = "Telegram"
        url = "https://t.me/your-username"
        icon = "i-mdi-telegram"
        color = "#2CA5E0"
        enable = false

    [[params.social]]
        name = "ORCID"
        url = "https://orcid.org/your-orcid-id"
        icon = "i-simple-orcid"
        color = "#A6CE39"
        enable = false

    [[params.social]]
        name = "Mastodon"
        url = "https://example.social/@your-username"
        icon = "i-carbon-logo-mastodon"
        color = "#6364FF"
        enable = false

    [[params.social]]
        name = "Bluesky"
        url = "https://bsky.app/profile/your-username"
        icon = "i-simple-bluesky"
        color = "#1DA1F2"
        enable = false

    [[params.social]]
        name = "Placeholder"
        url = "#"
        icon = "i-carbon-help"
        color = "#808080"
        enable = false

    [params.comments]
        enable = false
        type = "twikoo"

        [params.comments.twikoo]
            envId = "your-twikoo-env-id"

        [params.comments.waline]
            appId = ""
            appKey = ""

        [params.comments.giscus]
            repo = ""
            repoId = ""
            category = ""
            categoryID = ""

        [params.comments.artalk]
            serverURL = ""
            siteId = ""

    [params.beian]
        icp = ""
        gongan = ""
        moe = ""

[markup]
    [markup.goldmark]
        [markup.goldmark.extensions]
            [markup.goldmark.extensions.passthrough]
                enable = false
                [markup.goldmark.extensions.passthrough.delimiters]
                    block = [['$$', '$$']]
                    inline = [['$', '$']]