name = 'Hermeneutics'
license = 'MIT'
licenselink = 'https://codeberg.org/chlorine/hugo-theme-hermeneutics/src/branch/main/LICENSE'
description = 'But I call them all delusion —— beautiful delusion.'

# The home page of the theme, where the source can be found
homepage = 'https://codeberg.org/chlorine/hugo-theme-hermeneutics'

# If you have a running demo of the theme
demosite = 'https://chlor.me'

# Taxonomy terms
tags = ['Blog', 'Responsive', 'Minimal', 'Clean', 'Landing', 'UnoCSS']
features = ['MinimalJS', 'Twikoo', 'Algolia Docsearch', 'UnoCSS', 'Dark Mode']

# If the theme has a single author
[author]
  name = 'Chlorine'
  homepage = 'https://chlor.me'
